name: Extract RootFS from Docker Image

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Build Docker Image
        run: |
          docker buildx build --platform ${{ matrix.platform }} -f Dockerfile . -t fedora

      - name: Set Vars
        id: vars
        run: |
          echo "${{ matrix.platform }}" | awk -F'/' 'print { $2 }' >> "$GITHUB_OUTPUT"

      - name: Extract RootFS
        run: |
          docker buildx create --platform ${{ matrix.platform }} --name fedora fedora echo "Fedora Linux"
          docker export -o rootfs.${{ steps.vars.outputs.arch }}.tar fedora
          tar -cJf rootfs.${{ steps.vars.outputs.arch }}.tar.xz rootfs.${{ steps.vars.outputs.arch }}.tar
          docker rm fedora

      - name: Upload RootFS
        uses: actions/upload-artifact@v4
        with:
          name: rootfs.${{ steps.vars.outputs.arch }}
          path: rootfs.*.tar.xz

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download RootFS
        id: download-rootfs
        uses: actions/download-artifact@v4
        with:
          path: rootfs
          pattern: rootfs.*
          merge-multiple: true

      - name: List Files
        run: ls -R ${{ steps.download-rootfs.outputs.download-path }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.download-rootfs.outputs.download-path }}/*.tar.xz
